name = "juice"
description = "tech et progrmation"
license = "MIT"
homepage = "https://github.com/LeCodeEtMoi/my-site-web/"
min_version = "0.11.0"
demo = "https://LeCodeEtmOI.io"

[extra]

[author]
name = "Huhu teams"
homepage = "https://huhu.io"
