name = "juice"
description = "tech et progrmation"
license = "MIT"
homepage = "https://github.com/LeCodeEtMoi/my-site-web/"
discord = "https://discord.gg/GNdYT6yC"
min_version = "0.11.0"
demo = "https://LeCodeEtMoi.io"

[extra]

[author]
name = "Huhu teams"
homepage = "https://huhu.io"
