name = "juice"
description = "An intuitive, elegant, and lightweight Zola theme for product sites."
license = "MIT"
homepage = "https://github.com/LeCodeEtMoi/my-site-web"
min_version = "0.11.0"
demo = "https://LeCodeEtmOI.io"

[extra]

[author]
name = "Huhu teams"
homepage = "https://huhu.io"
